---
- name: "LampStack Installation & Configuration"
  hosts: all
  become: true
  vars:
    domain: www.example.com
    httpd_port: 80
    httpd_owner: apache
    httpd_group: apache
    mysql_root: "mysqlroot123"
    mysql_user: "wpuser"
    mysql_password: "wpuser123"
    mysql_database: "wordpress"
    wordpress_url: "https://wordpress.org/wordpress-4.7.7.tar.gz"
  tasks:
    
    - name: "Apache  - Installing httpd"
      yum:
        name: httpd
        state: present
   
    - name: "Apache  - Installing php & Extensions"
      yum:
        name:
          - php
          - php-mysql

    - name: "Apache  - Creating httpd.conf"
      template:
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
            
            
    - name: "Apache  - Creating Virtualhost"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/httpd/conf.d/{{ domain }}.conf"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
            
    - name: "Apache  - DocumentRoot Creation"
      file:
        path: "/var/www/html/{{ domain }}"
        state: directory
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
            
    - name: "Apache  - Creating index.php"
      copy:
        content: "<?php phpinfo(); ?>"
        dest: "/var/www/html/{{ domain }}/index.php"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
            
            
    - name: "Apache  - Service Restart/Enable"
      service:
        name: httpd
        state: restarted
        enabled: true
            
    - name: "Mariadb - Installation"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present
    
    - name: "Mariadb - Restart/Enable"
      service:
        name: mariadb
        state: restarted
        enabled: true
            
    - name: "Mariadb - Resetting Root Password"
      ignore_errors: true
      mysql_user:
        login_user: root
        login_password: ""
        user: root
        password: "{{ mysql_root }}"
        host_all: true
            
    - name: "Mariadb - Anonymous Users"
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        user: ""
        state: absent
        host_all: true
            
    - name: "Mariadb - Creating Extra Database"
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_database }}"
        state: present
            
    - name: "Mariadb - Creating Extra User"
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        user: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        state: present
        priv: "{{ mysql_database }}.*:ALL"

    - name: "Wordpress - Downloading Installation Files"
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/wordpress.tar.gz
            
    - name: "Wordpress - Extracting Installation File"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
    
    - name: "Worpress  - Copying Contents To DocumentRoot"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/html/{{ domain }}"
        remote_src: true
            
    - name: "Wordpress - Creating wp-config.php"
      template:
        src: wp-config.php.tmpl
        dest: "/var/www/html/{{ domain }}/wp-config.php"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
    
    - name: "Post-Installation Clean-up"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress/
        - /tmp/wordpress.tar.gz
        
    - name: "Post-Installation Restart"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - httpd
        - mariadb
